const router = require("express").Router()
const ownerRouter = require("./owner.routes")
console.log("index.route.js")
const bookRouter = require("./books.routes")
const adminRouter = require("./admins.routes")
const clientRouter = require("./clients.routes")
const categoryRouter = require("./categoies.routes")
const statusRouter = require("./status.routes")
const paaymentRouter = require("./payments.routes")
const contractRouter = require("./contracts.routes")
const reviewRouter = require("./reviews.routes")
const reservationRouter = require("./reservations.routes")

router.use("/owners", ownerRouter)
router.use("/books", bookRouter)
router.use("/admins", adminRouter)
router.use("/clients", clientRouter)
router.use("/category", categoryRouter)
router.use("/status", statusRouter)
router.use("/payments", paaymentRouter)
router.use("/contracts", contractRouter)
router.use("/reviews", reviewRouter)
router.use("/reservations", reservationRouter)

module.exports = router